PrisonHeadDirectory/PrisonHeadDirectory/Controllers/CasteController.cs
using System.Collections.Generic;
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace PrisonHeadDirectory.Controllers
{
    public class CasteController : Controller
    {
        private readonly ICasteDalService _casteDalService;

        public CasteController(ICasteDalService casteDalService)
        {
            _casteDalService = casteDalService;
        }
        
        [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<Caste> castes = _casteDalService.GetAll();
            return View(castes);
        }
        
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _casteDalService.Delete(id);
            return RedirectToAction("Get");
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Caste caste)
        {
            if (ModelState.IsValid)
            {
                _casteDalService.Add(caste);

                return RedirectToAction("Get");
            }

            return View(caste);
        }
        
        public string GetCasteName(int id)
        {
            Caste caste = _casteDalService.Get(id);
            if (caste is null)
            {
                return "-- не выбрано --";
            }
            
            return caste.Name;
        }
    }
}

PrisonHeadDirectory/PrisonHeadDirectory/Controllers/PrisonerController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;
using PrisonHeadDirectory.Models;

namespace PrisonHeadDirectory.Controllers
{
    public class PrisonerController : Controller
    {
        private readonly IPrisonerDalService _prisonerDalService;
        private readonly ICasteDalService _casteDalService;
        private readonly IArticleDalService _articleDalService;
        private readonly IRelativeDalService _relativeDalService;

        public PrisonerController(
            IPrisonerDalService prisonerDalService,
            ICasteDalService casteDalService,
            IArticleDalService articleDalService,
            IRelativeDalService relativeDalService)
        {
            _prisonerDalService = prisonerDalService;
            _casteDalService = casteDalService;
            _articleDalService = articleDalService;
            _relativeDalService = relativeDalService;
        }

        [HttpGet]
        public IActionResult Get(string searchStr = "", int articleId = 0, int casteId = 0,
            string arrestDateFromStr = null, string arrestDateToStr = null,
            string releaseDateFromStr = null, string releaseDateToStr = null)
        {
            searchStr ??= "";
            DateTime arrestDateFrom = arrestDateFromStr is null ? DateTime.MinValue
                : DateTime.Parse(arrestDateFromStr, CultureInfo.CurrentCulture);
            DateTime arrestDateTo = arrestDateToStr is null ? DateTime.MaxValue 
                : DateTime.Parse(arrestDateToStr, CultureInfo.CurrentCulture);
            DateTime releaseDateFrom = releaseDateFromStr is null ? DateTime.MinValue
                : DateTime.Parse(releaseDateFromStr, CultureInfo.CurrentCulture);
            DateTime releaseDateTo = releaseDateToStr is null ? DateTime.MaxValue 
                : DateTime.Parse(releaseDateToStr, CultureInfo.CurrentCulture);


            IEnumerable<Prisoner> prisoners = _prisonerDalService.GetPrisoners(searchStr);
            List<PrisonerShort> prisonerShorts = new List<PrisonerShort>();
            
            var castes = _casteDalService.GetAll().ToList();
            castes.Add(new Caste()
            {
                Name = "-- Не выбрано --",
                Id = 0
            });
            
            SelectList castesList = 
                new SelectList(castes, "Id", "Name", 0);

            var articles = _articleDalService.GetAll().ToList();
            articles.Add(new Article()
            {
                Name = "-- Не выбрано --",
                Id = 0
            });
            
            SelectList articlesList = 
                new SelectList(articles, "Id", "Name", 0);

            foreach (var prisoner in prisoners)
            {
                prisonerShorts.Add(new PrisonerShort()
                {
                        Name = prisoner.Name,
                        Surname = prisoner.Surname,
                        MiddleName = prisoner.MiddleName,
                        ArrestDate = prisoner.ArrestDate,
                        ReleaseDate = prisoner.ReleaseDate,
                        ArticleIds = prisoner.Articles.Select(a => a.Id).ToList(),
                        CasteId = prisoner.CasteId,
                        Id = prisoner.Id
                });
            }

            if (casteId != 0)
            {
                prisonerShorts = prisonerShorts.Where(ps => ps.CasteId == casteId).ToList();
            }
            
            if (articleId != 0)
            {
                prisonerShorts = prisonerShorts.Where(ps => ps.ArticleIds.Contains(articleId)).ToList();
            }

            prisonerShorts = prisonerShorts
                .Where(ps => DateTime.Compare(ps.ArrestDate, (DateTime)arrestDateFrom) > 0 
                             && DateTime.Compare(ps.ArrestDate, (DateTime)arrestDateTo) < 0
                             && DateTime.Compare(ps.ReleaseDate, (DateTime)releaseDateFrom) > 0
                             && DateTime.Compare(ps.ReleaseDate, (DateTime)releaseDateTo) < 0)
                .ToList();

            ViewBag.Articles = articlesList;
            ViewBag.Castes = castesList;

            return View(prisonerShorts);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Prisoner prisoner)
        {
            if (ModelState.IsValid)
            {
                _prisonerDalService.Create(prisoner);
                return RedirectToAction("Edit", new {id = prisoner.Id});
            }

            return View(prisoner);
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Prisoner prisoner = _prisonerDalService.Get(id);

            var castes = _casteDalService.GetAll().ToList();

            castes.Add(new Caste()
            {
                Name = "-- Не выбрано --",
                Id = 0
            });

            if (!castes.Select(c => c.Id).Contains(prisoner.CasteId))
            {
                prisoner.CasteId = 0;
            }

            SelectList castesList = 
                new SelectList(castes, "Id", "Name", prisoner.CasteId);
            
            ViewBag.Castes = castesList;
            
            return View(prisoner);
        }
        
        [HttpPost]
        public IActionResult Edit(Prisoner prisoner)
        {
            if (ModelState.IsValid)
            {
                Prisoner currentPrisoner = _prisonerDalService.Get(prisoner.Id);

                if (currentPrisoner is null)
                {
                    return View(prisoner);
                }

                prisoner.Articles = currentPrisoner.Articles;
                _prisonerDalService.Update(prisoner);
                
                return RedirectToAction("Edit", new {id = prisoner.Id});
            }

            return View(prisoner);
        }
        
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _prisonerDalService.Delete(id);
            return RedirectToAction("Get");
        }
        
        [HttpGet]
        public IActionResult DisplayPrisonerInfo(int id)
        {
            Prisoner prisoner = _prisonerDalService.Get(id);
            return PartialView("_PrisonerInfo", prisoner);
        }

        [HttpGet]
        public IActionResult DeleteRelative(int id, int prisonerId)
        {
            _relativeDalService.Delete(id);
            return RedirectToAction("Edit", new {id = prisonerId});
        }
        
        [HttpPost]
        public IActionResult CreateRelative(Relative relative)
        {
            _relativeDalService.Add(relative);
            return null;
        }
        
        public IActionResult DeleteArticle(int id, int prisonerId)
        {
            Prisoner prisoner = _prisonerDalService.Get(prisonerId);
            prisoner.Articles.Remove(prisoner.Articles.FirstOrDefault(a => a.Id == id));
            
            _prisonerDalService.Update(prisoner);
            
            return RedirectToAction("Edit", new {id = prisonerId});
        }
        
        [HttpGet]
        public IActionResult AddArticle(int prisonerId)
        {
            Prisoner prisoner = _prisonerDalService.Get(prisonerId);

            if (prisoner is null)
            {
                return RedirectToAction("Edit", new {id = prisonerId});
            }
            
            return RedirectToAction("SelectArticle", "Article", new
            {
                nextAction = Url.Action("AddArticle", new {prisonerId = prisonerId}),
                exceptIds = prisoner.Articles.Select(a => a.Id).ToList()
            });
        }
        
        [HttpPost]
        public IActionResult AddArticle(int prisonerId, int articleId)
        {
            Prisoner prisoner = _prisonerDalService.Get(prisonerId);
            Article article = _articleDalService.Get(articleId);
            
            if (prisoner is null || article is null)
            {
                return Json(new { redirectToUrl = Url.Action("Edit", new {id = prisonerId}) });
            }
            
            prisoner.Articles.Add(article);
            _prisonerDalService.Update(prisoner);
            
            return Json(new { redirectToUrl = Url.Action("Edit", new {id = prisonerId}) });
        }

        [HttpGet] 
        public FileResult GetExcel(IEnumerable<int> prisonerIds)
        {
            List<Prisoner> prisoners = new List<Prisoner>();

            foreach (var id in prisonerIds)
            {
                prisoners.Add(_prisonerDalService.Get(id));
            }
            
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            
            ExcelPackage excelPackage = new ExcelPackage();
            ExcelWorksheet prisonersWorksheet = excelPackage.Workbook.Worksheets.Add("Заключенные");

            prisonersWorksheet.Cells["A1"].Value = "Фамилия";
            prisonersWorksheet.Cells["B1"].Value = "Имя";
            prisonersWorksheet.Cells["C1"].Value = "Отчество";
            prisonersWorksheet.Cells["D1"].Value = "Дата заключения";
            prisonersWorksheet.Cells["E1"].Value = "Дата освобождения";
            prisonersWorksheet.Cells["F1"].Value = "Каста";
            prisonersWorksheet.Cells["G1"].Value = "Статьи";
            prisonersWorksheet.Cells[1, 1, 1, 7].AutoFitColumns();
            prisonersWorksheet.Cells[1, 1, 1, 7].Style.Font.Bold = true;
            prisonersWorksheet.Column(4).Style.Numberformat.Format = "dd-MM-yyyy";
            prisonersWorksheet.Column(5).Style.Numberformat.Format = "dd-MM-yyyy";

            int currentRow = 1;
            foreach (var prisoner in prisoners)
            {
                currentRow++;

PrisonHeadDirectory/PrisonHeadDirectory/Controllers/RelativeController.cs
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace PrisonHeadDirectory.Controllers
{
    public class RelativeController : Controller
    {
        private readonly IRelativeDalService _relativeDalService;

        public RelativeController(IRelativeDalService relativeDalService)
        {
            _relativeDalService = relativeDalService;
        }

        [HttpGet]
        public IActionResult Create(int prisonerId)
        {
            ViewBag.PrisonerId = prisonerId;
            return View(new Relative());
        }
        
        [HttpPost]
        public IActionResult Create(Relative relative)
        {
            if (ModelState.IsValid)
            {
                _relativeDalService.Add(relative);

                return RedirectToAction("Edit", "Prisoner", new {id = relative.PrisonerId});
            }

            return View(relative);
        }
        
        [HttpGet]
        public IActionResult DisplayRelativeInfo(int id)
        {
            Relative relative = _relativeDalService.Get(id);
            return PartialView("_RelativeInfo", relative);
        }
    }
}

PrisonHeadDirectory/PrisonHeadDirectory/Views/Prisoner/Create.cshtml
@model Core.Prisoner

@{
    ViewData["Title"] = "Добавить Заключенного";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить заключенного</h1>

<h4>Заключенный</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Имя</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Отчество</label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Фамилия</label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Дата ареста</label>
                <input asp-for="ArrestDate" type="text" id="arrest-date" class="form-control" />
                <span asp-validation-for="ArrestDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Дата освобождения</label>
                <input asp-for="ReleaseDate" type="text" id="release-date" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Камера</label>
                <input asp-for="Cell" class="form-control" />
                <span asp-validation-for="Cell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Примечания</label>
                <textarea asp-for="Notes" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Get">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function (){
        $("#arrest-date").datepicker({ format: 'dd/mm/yyyy' });
        $("#release-date").datepicker({ format: 'dd/mm/yyyy' });
    });
</script>

PrisonHeadDirectory/PrisonHeadDirectory/Views/Prisoner/Edit.cshtml
@using Core
@model Core.Prisoner

@{
    ViewData["Title"] = "Редактировать заключенного";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 xmlns="http://www.w3.org/1999/html">Редактировать заключенного</h1>

<div>
    <a asp-action="Get">Вернуться к списку</a>
</div>

<h4>Заключенный</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Имя</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Отчество</label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Фамилия</label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Дата ареста</label>
                <input asp-for="ArrestDate" type="text" id="arrest-date" class="form-control" />
                <span asp-validation-for="ArrestDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Дата освобождения</label>
                <input asp-for="ReleaseDate" type="text" id="release-date" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Камера</label>
                <input asp-for="Cell" class="form-control" />
                <span asp-validation-for="Cell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Примечания</label>
                <textarea asp-for="Notes" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <hr>
            <div class="form-group">
                <label class="control-label">Место в тюремной иерархии</label>
                @Html.DropDownListFor(model => model.CasteId, ViewBag.Castes as SelectList,  new
                {
                    @class = "form-control"
                })
                <span asp-validation-for="CasteId" class="text-danger"></span>
            </div>
            <hr>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
            <hr>
            <div id="article-container">
                @await Html.PartialAsync("_GetPrisonerArticles", Model)
                <input class="btn btn-link" type="button" onclick="showSelectArticle()" value="Добавить статью"/>
            </div>
            <hr>
            <div id="relative-container">
                @await Html.PartialAsync("_GetRelatives", Model.Relatives)
                @Html.ActionLink("Добавить родственника", "Create", "Relative", new {prisonerId = Model.Id})
            </div>
        </form>
    </div>
</div>

<div id="modal-article-container"></div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
    $(document).ready(function (){
        $("#arrest-date").datepicker({ format: 'dd/mm/yyyy' });
        $("#release-date").datepicker({ format: 'dd/mm/yyyy' });
    });
    
    function showSelectArticle() {
        $("#modal-article-container").load("@Url.Action("AddArticle", "Prisoner", new {prisonerId = Model.Id})");
    }
</script>

PrisonHeadDirectory/PrisonHeadDirectory/Views/Prisoner/Get.cshtml
@model IEnumerable<PrisonerShort>

@{
    ViewData["Title"] = "Пользователи";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    tbody tr {
        cursor: pointer;
    }
    tbody tr:hover {
        background: lightgray;
    }
    select {
        width: auto !important
    }
</style>
<h1>Заключенные</h1>
<hr>
<p>
    <a asp-action="Create">Добавить заключенного</a>
</p>
<hr>
<button class="btn btn-primary mb-3" type="button" data-toggle="collapse" 
        data-target="#filter-collapse" aria-expanded="false" aria-controls="filter-collapse">
    Поиск по фильтрам
</button>

@Html.ActionLink("Сохранить выборку в Excel", "GetExcel", "Prisoner", 
    new { prisonerIds = Model.Select(p => p.Id).ToList() }, 
    new { @class = "btn btn-success mb-3" })

<div class="row collapse" id="filter-collapse">
    @using (Html.BeginForm("Get", "Prisoner", FormMethod.Get, new
    {
        @class = "col-md-12",
        @autocomplete = "off"
    }))
    {
        <div class="row">
            <input class="form-control col-md-12 m-1" value="" name="searchStr" 
                   type="text" id="searchStrInput" placeholder="Поиск по ФИО"/>
        </div>
        <hr>
        <div class="row">
            <div class="form-group col-md-12">
                <label class="control-label">Место в тюремной иерархии</label>
                @Html.DropDownList("casteId", ViewBag.Castes as SelectList, new
                {
                    @class = "form-control w-100"
                })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label class="control-label">Статья</label>
                @Html.DropDownList("articleId", ViewBag.Articles as SelectList, new
                {
                    @class = "form-control w-100"
                })
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="form-group col-md-12">
                <label class="control-label font-weight-bold">Дата заключения</label>
                <p>С</p>
                <input name="arrestDateFromStr" type="text" id="arrest-date-from" class="form-control" />
                <p>До</p>
                <input name="arrestDateToStr" type="text" id="arrest-date-to" class="form-control" />
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="form-group col-md-12">
                <label class="control-label font-weight-bold">Дата освобождения</label>
                <p>С</p>
                <input name="releaseDateFromStr" type="text" id="release-date-from" class="form-control" />
                <p>До</p>
                <input name="releaseDateToStr" type="text" id="release-date-to" class="form-control" />
            </div>
        </div>
        <hr>
        <input class="btn btn-primary col-md-3 m-1 mb-3" type="submit" id="searchButton" value="Поиск" />
    }
</div>
<table class="table">
    <thead>
    <tr>
        <th>
            Имя
        </th>
        <th>
            Отчество
        </th>
        <th>
            Фамилия
        </th>
        <th>
            Дата заключения
        </th>
        <th>
            Дата освобождения
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr onclick="displayPrisonerInfo(@item.Id)">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @{
                    var arrestDate = item.ArrestDate.ToShortDateString();
                    @Html.DisplayFor(modelItem => arrestDate)
                }
            </td>
            <td>
                @{
                    var releaseDate = item.ReleaseDate.ToShortDateString();
                    @Html.DisplayFor(modelItem => releaseDate);
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    </tbody>
</table>
<div id="modal-container"></div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#arrest-date-from").datepicker({ format: 'dd/mm/yyyy' });
        $("#arrest-date-to").datepicker({ format: 'dd/mm/yyyy' });
        $("#release-date-from").datepicker({ format: 'dd/mm/yyyy' });
        $("#release-date-to").datepicker({ format: 'dd/mm/yyyy' });
    });

    function displayPrisonerInfo(id) {
        $("#modal-container").load('@Url.Action("DisplayPrisonerInfo", "Prisoner")?id='+id);
    }
</script>

PrisonHeadDirectory/PrisonHeadDirectory/Views/Prisoner/_GetPrisonerArticles.cshtml
@model Core.Prisoner

<h3>Статьи</h3>

<table class="table">
    <thead>
    <tr>
        <th>
            Название
        </th>
        <th>
            Номер
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Articles) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.ActionLink("Удалить", "DeleteArticle", "Prisoner", 
                    new {id = item.Id, prisonerId = Model.Id})
            </td>
        </tr>
    }
    </tbody>
</table>

PrisonHeadDirectory/PrisonHeadDirectory/Views/Prisoner/_GetRelatives.cshtml
@model IEnumerable<Core.Relative>

<h3>Родственники</h3>

<table class="table">
    <thead>
    <tr>
        <th>
            Имя
        </th>
        <th>
            Отчество
        </th>
        <th>
            Фамилия
        </th>
        <th>
            Роль
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr onclick="displayRelativeInfo(@item.Id)">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RelativeRole)
            </td>
            <td>
                @Html.ActionLink("Удалить", "DeleteRelative", "Prisoner", 
                    new {id = item.Id, prisonerId = item.PrisonerId})
            </td>
        </tr>
    }
    </tbody>
</table>
<div id="modal-relative-container"></div>

<script type="text/javascript">
    function displayRelativeInfo(id) {
        $("#modal-relative-container").load('@Url.Action("DisplayRelativeInfo", "Relative")?id='+id);
    }
</script>

PrisonHeadDirectory/PrisonHeadDirectory/Views/Prisoner/_PrisonerInfo.cshtml
@model Core.Prisoner

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="prisoner-modal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Заключенный</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Имя: @Model.Name</p>
                <p>Отчество: @Model.MiddleName</p>
                <p>Фамилия: @Model.Surname</p>
                <p>Дата ареста: @Model.ArrestDate.ToShortDateString()</p>
                <p>Дата освобождения: @Model.ReleaseDate.ToShortDateString()</p>
                <p>Камера: @Model.Cell</p>
                <p>Каста: <span id="caste-area"></span></p>
                <div id="relative-container">
                    @await Html.PartialAsync("_GetRelatives", Model.Relatives)
                </div>
                <div id="article-container">
                    @await Html.PartialAsync("_GetPrisonerArticles", Model)
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $("#caste-area").load('@Url.Action("GetCasteName", "Caste")?id='+@Model.CasteId);
    $("#prisoner-modal").modal("show");
</script>