PrisonHeadDirectory/PrisonHeadDirectory/Controllers/ArticleController.cs
using System.Collections.Generic;
using System.Linq;
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace PrisonHeadDirectory.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleDalService _articleDalService;

        public ArticleController(IArticleDalService articleDalService)
        {
            _articleDalService = articleDalService;
        }
        
        [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<Article> articles = _articleDalService.GetAll();
            return View(articles);
        }
        
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _articleDalService.Delete(id);
            return RedirectToAction("Get");
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Article article)
        {
            if (ModelState.IsValid)
            {
                _articleDalService.Add(article);

                return RedirectToAction("Get");
            }

            return View(article);
        }

        public string GetArticleNames(int[] ids)
        {
            List<Article> articles = new List<Article>();

            foreach (var id in ids)
            {
                Article article = _articleDalService.Get(id);

                if (article is null)
                {
                    continue;
                }
                
                articles.Add(article);
            }

            if (!articles.Any())
            {
                return "-- не выбрано --";
            }

            return string.Join(", ", articles.Select(a => a.Name));
        }
        
        [HttpGet]
        public IActionResult SelectArticle(string nextAction, IEnumerable<int> exceptIds)
        {
            ViewBag.NextAction = nextAction;
            IEnumerable<Article> articles = _articleDalService.GetAll()
               .Where(a => !exceptIds.Contains(a.Id)).ToList();
            
            return PartialView("_SelectArticle", articles);
        }
    }
}

PrisonHeadDirectory/PrisonHeadDirectory/Controllers/CasteController.cs
using System.Collections.Generic;
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace PrisonHeadDirectory.Controllers
{
    public class CasteController : Controller
    {
        private readonly ICasteDalService _casteDalService;

        public CasteController(ICasteDalService casteDalService)
        {
            _casteDalService = casteDalService;
        }
        
        [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<Caste> castes = _casteDalService.GetAll();
            return View(castes);
        }
        
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _casteDalService.Delete(id);
            return RedirectToAction("Get");
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Caste caste)
        {
            if (ModelState.IsValid)
            {
                _casteDalService.Add(caste);

                return RedirectToAction("Get");
            }

            return View(caste);
        }
        
        public string GetCasteName(int id)
        {
            Caste caste = _casteDalService.Get(id);
            if (caste is null)
            {
                return "-- не выбрано --";
            }
            
            return caste.Name;
        }
    }
}

PrisonHeadDirectory/PrisonHeadDirectory/Controllers/PrisonerController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;
using PrisonHeadDirectory.Models;

namespace PrisonHeadDirectory.Controllers
{
    public class PrisonerController : Controller
    {
        private readonly IPrisonerDalService _prisonerDalService;
        private readonly ICasteDalService _casteDalService;
        private readonly IArticleDalService _articleDalService;
        private readonly IRelativeDalService _relativeDalService;

        public PrisonerController(
            IPrisonerDalService prisonerDalService,
            ICasteDalService casteDalService,
            IArticleDalService articleDalService,
            IRelativeDalService relativeDalService)
        {
            _prisonerDalService = prisonerDalService;
            _casteDalService = casteDalService;
            _articleDalService = articleDalService;
            _relativeDalService = relativeDalService;
        }

        [HttpGet]
        public IActionResult Get(string searchStr = "", int articleId = 0, int casteId = 0,
            string arrestDateFromStr = null, string arrestDateToStr = null,
            string releaseDateFromStr = null, string releaseDateToStr = null)
        {
            searchStr ??= "";
            DateTime arrestDateFrom = arrestDateFromStr is null ? DateTime.MinValue
                : DateTime.Parse(arrestDateFromStr, CultureInfo.CurrentCulture);
            DateTime arrestDateTo = arrestDateToStr is null ? DateTime.MaxValue 
                : DateTime.Parse(arrestDateToStr, CultureInfo.CurrentCulture);
            DateTime releaseDateFrom = releaseDateFromStr is null ? DateTime.MinValue
                : DateTime.Parse(releaseDateFromStr, CultureInfo.CurrentCulture);
            DateTime releaseDateTo = releaseDateToStr is null ? DateTime.MaxValue 
                : DateTime.Parse(releaseDateToStr, CultureInfo.CurrentCulture);


            IEnumerable<Prisoner> prisoners = _prisonerDalService.GetPrisoners(searchStr);
            List<PrisonerShort> prisonerShorts = new List<PrisonerShort>();
            
            var castes = _casteDalService.GetAll().ToList();
            castes.Add(new Caste()
            {
                Name = "-- Не выбрано --",
                Id = 0
            });
            
            SelectList castesList = 
                new SelectList(castes, "Id", "Name", 0);

            var articles = _articleDalService.GetAll().ToList();
            articles.Add(new Article()
            {
                Name = "-- Не выбрано --",
                Id = 0
            });
            
            SelectList articlesList = 
                new SelectList(articles, "Id", "Name", 0);

            foreach (var prisoner in prisoners)
            {
                prisonerShorts.Add(new PrisonerShort()
                {
                        Name = prisoner.Name,
                        Surname = prisoner.Surname,
                        MiddleName = prisoner.MiddleName,
                        ArrestDate = prisoner.ArrestDate,
                        ReleaseDate = prisoner.ReleaseDate,
                        ArticleIds = prisoner.Articles.Select(a => a.Id).ToList(),
                        CasteId = prisoner.CasteId,
                        Id = prisoner.Id
                });
            }

            if (casteId != 0)
            {
                prisonerShorts = prisonerShorts.Where(ps => ps.CasteId == casteId).ToList();
            }
            
            if (articleId != 0)
            {
                prisonerShorts = prisonerShorts.Where(ps => ps.ArticleIds.Contains(articleId)).ToList();
            }

            prisonerShorts = prisonerShorts
                .Where(ps => DateTime.Compare(ps.ArrestDate, (DateTime)arrestDateFrom) > 0 
                             && DateTime.Compare(ps.ArrestDate, (DateTime)arrestDateTo) < 0
                             && DateTime.Compare(ps.ReleaseDate, (DateTime)releaseDateFrom) > 0
                             && DateTime.Compare(ps.ReleaseDate, (DateTime)releaseDateTo) < 0)
                .ToList();

            ViewBag.Articles = articlesList;
            ViewBag.Castes = castesList;

            return View(prisonerShorts);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Prisoner prisoner)
        {
            if (ModelState.IsValid)
            {
                _prisonerDalService.Create(prisoner);
                return RedirectToAction("Edit", new {id = prisoner.Id});
            }

            return View(prisoner);
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Prisoner prisoner = _prisonerDalService.Get(id);

            var castes = _casteDalService.GetAll().ToList();

            castes.Add(new Caste()
            {
                Name = "-- Не выбрано --",
                Id = 0
            });

            if (!castes.Select(c => c.Id).Contains(prisoner.CasteId))
            {
                prisoner.CasteId = 0;
            }

            SelectList castesList = 
                new SelectList(castes, "Id", "Name", prisoner.CasteId);
            
            ViewBag.Castes = castesList;
            
            return View(prisoner);
        }
        
        [HttpPost]
        public IActionResult Edit(Prisoner prisoner)
        {
            if (ModelState.IsValid)
            {
                Prisoner currentPrisoner = _prisonerDalService.Get(prisoner.Id);

                if (currentPrisoner is null)
                {
                    return View(prisoner);
                }

                prisoner.Articles = currentPrisoner.Articles;
                _prisonerDalService.Update(prisoner);
                
                return RedirectToAction("Edit", new {id = prisoner.Id});
            }

            return View(prisoner);
        }
        
        [HttpGet]
        public IActionResult Delete(int id)
        {
            _prisonerDalService.Delete(id);
            return RedirectToAction("Get");
        }
        
        [HttpGet]
        public IActionResult DisplayPrisonerInfo(int id)
        {
            Prisoner prisoner = _prisonerDalService.Get(id);
            return PartialView("_PrisonerInfo", prisoner);
        }

        [HttpGet]
        public IActionResult DeleteRelative(int id, int prisonerId)
        {
            _relativeDalService.Delete(id);
            return RedirectToAction("Edit", new {id = prisonerId});
        }
        
        [HttpPost]
        public IActionResult CreateRelative(Relative relative)
        {
            _relativeDalService.Add(relative);
            return null;
        }
        
        public IActionResult DeleteArticle(int id, int prisonerId)
        {
            Prisoner prisoner = _prisonerDalService.Get(prisonerId);
            prisoner.Articles.Remove(prisoner.Articles.FirstOrDefault(a => a.Id == id));
            
            _prisonerDalService.Update(prisoner);
            
            return RedirectToAction("Edit", new {id = prisonerId});
        }
        
        [HttpGet]
        public IActionResult AddArticle(int prisonerId)
        {
            Prisoner prisoner = _prisonerDalService.Get(prisonerId);

            if (prisoner is null)
            {
                return RedirectToAction("Edit", new {id = prisonerId});
            }
            
            return RedirectToAction("SelectArticle", "Article", new
            {
                nextAction = Url.Action("AddArticle", new {prisonerId = prisonerId}),
                exceptIds = prisoner.Articles.Select(a => a.Id).ToList()
            });
        }
        
        [HttpPost]
        public IActionResult AddArticle(int prisonerId, int articleId)
        {
            Prisoner prisoner = _prisonerDalService.Get(prisonerId);
            Article article = _articleDalService.Get(articleId);
            
            if (prisoner is null || article is null)
            {
                return Json(new { redirectToUrl = Url.Action("Edit", new {id = prisonerId}) });
            }
            
            prisoner.Articles.Add(article);
            _prisonerDalService.Update(prisoner);
            
            return Json(new { redirectToUrl = Url.Action("Edit", new {id = prisonerId}) });
        }

        [HttpGet] 
        public FileResult GetExcel(IEnumerable<int> prisonerIds)
        {
            List<Prisoner> prisoners = new List<Prisoner>();

            foreach (var id in prisonerIds)
            {
                prisoners.Add(_prisonerDalService.Get(id));
            }
            
            ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            
            ExcelPackage excelPackage = new ExcelPackage();
            ExcelWorksheet prisonersWorksheet = excelPackage.Workbook.Worksheets.Add("Заключенные");

            prisonersWorksheet.Cells["A1"].Value = "Фамилия";
            prisonersWorksheet.Cells["B1"].Value = "Имя";
            prisonersWorksheet.Cells["C1"].Value = "Отчество";
            prisonersWorksheet.Cells["D1"].Value = "Дата заключения";
            prisonersWorksheet.Cells["E1"].Value = "Дата освобождения";
            prisonersWorksheet.Cells["F1"].Value = "Каста";
            prisonersWorksheet.Cells["G1"].Value = "Статьи";
            prisonersWorksheet.Cells[1, 1, 1, 7].AutoFitColumns();
            prisonersWorksheet.Cells[1, 1, 1, 7].Style.Font.Bold = true;
            prisonersWorksheet.Column(4).Style.Numberformat.Format = "dd-MM-yyyy";
            prisonersWorksheet.Column(5).Style.Numberformat.Format = "dd-MM-yyyy";

            int currentRow = 1;
            foreach (var prisoner in prisoners)
            {
                currentRow++;

PrisonHeadDirectory/PrisonHeadDirectory/Controllers/StatisticsController.cs
using System.Collections.Generic;
using System.Linq;
using Core;
using DAL.Abstractions;
using Microsoft.AspNetCore.Mvc;
using PrisonHeadDirectory.Models;

namespace PrisonHeadDirectory.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly IPrisonerDalService _prisonerDalService;
        private readonly ICasteDalService _casteDalService;
        private readonly IArticleDalService _articleDalService;
        private readonly IRelativeDalService _relativeDalService;

        public StatisticsController(
            IPrisonerDalService prisonerDalService,
            ICasteDalService casteDalService,
            IArticleDalService articleDalService,
            IRelativeDalService relativeDalService)
        {
            _prisonerDalService = prisonerDalService;
            _casteDalService = casteDalService;
            _articleDalService = articleDalService;
            _relativeDalService = relativeDalService;
        }
        
        [HttpGet]
        public IActionResult Get()
        {
            var prisoners = _prisonerDalService.GetPrisoners().ToList();
            var castes = _casteDalService.GetAll();
            var articles = _articleDalService.GetAll();

            StatisticsViewModel statistics = new StatisticsViewModel()
            {
                TotalPrisoners = prisoners.Count(),
                
                ArticlePrisoners = articles.ToDictionary(a => a,
                    a => prisoners.Count(p => p.Articles
                        .Select(art => art.Id).Contains(a.Id))),
                
                CastePrisoners = castes.GroupJoin(prisoners,
                    c => c.Id,
                    p => p.CasteId,
                    (c, prs) => new
                    {
                        Caste = c,
                        PrisonerCount = prs.Count()
                    }).ToDictionary(el => el.Caste,
                    el => el.PrisonerCount),
                
                TermPrisoners = new Dictionary<string, int>(new List<KeyValuePair<string, int>>(
                    new KeyValuePair<string, int>[]
                    {
                        new KeyValuePair<string, int>("< 1 года", prisoners
                            .Count(p => (p.ReleaseDate - p.ArrestDate).TotalDays < 365)),
                        new KeyValuePair<string, int>(">= 1 и < 10 лет", prisoners
                            .Count(p => (p.ReleaseDate - p.ArrestDate).TotalDays is < 3650 and >= 365)),
                        new KeyValuePair<string, int>(">= 10 лет", prisoners
                            .Count(p => (p.ReleaseDate - p.ArrestDate).TotalDays > 3650)),
                    }))
            };
            
            return View(statistics);
        }
    }
}

PrisonHeadDirectory/PrisonHeadDirectory/Views/Shared/_Layout.cshtml
@using System.Net
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prison Head Directory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prison Head Directory</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Prisoner" asp-action="Get">Заключенные</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Get">Статьи</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Caste" asp-action="Get">Касты</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Get">Статистика</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Выход</a>
                            </li>
                        </ul>
                    }
                    @if (User.IsInRole("admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Get">Пользователи</a>
                            </li>
                        </ul>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Авторизация</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Prison Head Directory
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>